field: 1620eeee-116e-4a05-8fd6-23261ce30266 # Call To Action Start Repairing
fieldLayouts:
  d93124a4-fac1-4a6c-9591-37302f2b9975:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f0f65d9d-0ea5-4b76-b0b7-68a7efc76713 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a557c088-7b87-4da3-9ad0-018e703b1c1b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 12e6be53-916a-4aaa-b1cf-4846f1eeb668 # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2cf73473-9b97-4582-b1f7-2288c2f0bacd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 89423632-3653-4d19-8a9d-c9c8de51c5a9 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c9c3607-8d1f-4e2b-a739-83c3aab0c432
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 268a9e55-0edb-459a-9bde-e44e3f6e7fcd # Call To Action
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28dbd084-90f2-4f11-8120-7345d3339019
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 356152ad-e982-4276-a01c-6cacb2cddfe9
        userCondition: null
fields:
  12e6be53-916a-4aaa-b1cf-4846f1eeb668: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  268a9e55-0edb-459a-9bde-e44e3f6e7fcd: # Call To Action
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: cta
    instructions: null
    name: 'Call To Action'
    searchable: true
    settings:
      blockTypeFields: 0
      changedFieldIndicator: null
      columns:
        __assoc__:
          -
            - 2b247bc0-1dcc-4ce0-8ae5-cec752c75b86 # Link
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_19_cta}}'
      fieldLayout: matrix
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  89423632-3653-4d19-8a9d-c9c8de51c5a9: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: false
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:979c3eeb-f99a-4ca1-bcbe-ce9298a4e4ca' # Files
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:979c3eeb-f99a-4ca1-bcbe-ce9298a4e4ca' # Files
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  f0f65d9d-0ea5-4b76-b0b7-68a7efc76713: # Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: blockTitle
    instructions: null
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: block
name: Block
sortOrder: 1
