field: a5a75022-d8bf-4689-a25f-fde7cb280dbf # What can you do?
fieldLayouts:
  a9f05407-3929-4fa4-a406-a4e5a09c7cfc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7e4ed55f-00f6-4e9a-a961-17cf41c1a368 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6115b39c-3770-46f9-87ed-b7d5366b8340
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d808c207-d862-4cb1-8b04-f256a30a9e0b # Options
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4f433b4-1c91-482d-9cf5-3ac8a0d94391
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f1226d7d-d24b-4121-8541-3d656b54ae0d
        userCondition: null
fields:
  7e4ed55f-00f6-4e9a-a961-17cf41c1a368: # Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: blockTitle
    instructions: null
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  d808c207-d862-4cb1-8b04-f256a30a9e0b: # Options
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: options
    instructions: null
    name: Options
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: null
      columns:
        __assoc__:
          -
            - e5151f73-1061-48e4-b1bc-f2c53ed9837b # Title
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - ce78e94c-276c-4354-884b-e9080c353bb5 # Image
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 3e99b79c-1ba7-4d00-ac1e-fa5fc25f4e1b # Call to actions
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_21_options}}'
      fieldLayout: matrix
      maxRows: 3
      minRows: 1
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: block
name: Block
sortOrder: 1
