field: e748a9e9-20a3-4995-8e2f-bf2ea91b50d0 # Call to actions
fieldLayouts:
  e9c9ffa6-ac06-4aa0-bd9b-f8f9bb354fbc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 071b3b21-f83e-408d-adf6-ca45435c9fc9 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e7ad0b1-6585-4870-a690-94c6963161af
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 39a531c4-218e-49f1-8c39-ae32085185eb
        userCondition: null
fields:
  071b3b21-f83e-408d-adf6-ca45435c9fc9: # Link
    columnSuffix: islqowzb
    contentColumnType: text
    fieldGroup: null
    handle: linkit
    instructions: null
    name: Link
    searchable: true
    settings:
      allowClass: '1'
      allowCustomText: '1'
      allowTarget: ''
      allowedLinkNames: '*'
      class: null
      classes: null
      defaultLinkName: asset
      defaultText: ''
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\cta\fields\CTAField
handle: cta
name: CTA
sortOrder: 1
