field: 56d715d0-6a9d-4562-9c66-e5b4caad7f44 # Content Builder
fieldLayouts:
  4bb37325-4657-4b4b-a37d-a9601263cf72:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d66ffcef-8ccc-4e89-9e36-bce49e0dd17a # Video
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a39b025-9882-4de3-99b1-de5ce0ed44ce
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fca40313-aa0d-4206-a530-c638a5166f69 # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b145e8c6-c8d3-47ef-be28-68948f44da5f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 363f5d62-9115-439a-9b37-74f33fb56703
        userCondition: null
fields:
  d66ffcef-8ccc-4e89-9e36-bce49e0dd17a: # Video
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: video
    instructions: 'Paste the URL of a YouTube or Vimeo video. '
    name: Video
    searchable: true
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Url
  fca40313-aa0d-4206-a530-c638a5166f69: # Background Color
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColor
    instructions: 'Select the background color of the whole section.'
    name: 'Background Color'
    searchable: true
    settings:
      dataSet: 'Background colors'
      type: dropdown
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
handle: video
name: Video
sortOrder: 4
