fieldLayouts:
  5287291e-39ee-4c67-bfd2-874c8388ec37:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f6da0fd3-f3db-4bae-9bf0-57d807d83fa3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b5de6dcf-80e6-48e2-b846-0dab7f35c4c8 # Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c6b4c0b2-e0c2-4f41-b7f6-f2f3c644a16c
            userCondition: null
            warning: null
            width: 100
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'The repair registration form will be rendered below the intro.'
            type: craft\fieldlayoutelements\Tip
            uid: 39c65605-37ed-402a-9e11-e6d26f706f69
            userCondition: null
          -
            elementCondition: null
            fieldUid: b8691cd7-cac5-4aa2-82a1-a8c4d6da948b # Form Title
            instructions: 'Enter a title for the form'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1b48351-41ff-4fda-ac51-00af32e82ffb
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 6f1e2995-beeb-42e1-8534-60d482013514 # Redirect page
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 553a7b8c-3c91-4013-b35e-1dfae8d0f9f6
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 8f6c468a-6f52-4061-af89-56c3d23a34af
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4a2bad07-8d89-4689-b0bf-774eed764660 # Overview title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d2b4dd5-6ecb-46f2-aa8a-430ef683a776
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f8a6ddc-4ab7-4f9f-a2ea-72c6cb387f38 # Overview description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33171019-204e-4d67-8f57-b0a53c59aceb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 15ed2b72-8955-4cec-93f8-9736a9e50e80 # Overview image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9013d62-5484-4fa7-a9e2-3919f90dfd66
            userCondition: null
            warning: null
            width: 100
        name: Overview
        uid: f79db504-6aae-4630-b580-5aff1c4e912e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 685530fc-e1f1-4be1-813b-ebf9ac3aa108 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ebef06f3-6d5a-4b3a-a5a5-3c09d372f72f
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 7fc705c2-933b-493a-8fa1-6f5fd98d644d
        userCondition: null
handle: diyRepair
hasTitleField: true
name: 'DIY Repair'
section: 7cfd7e3b-194d-4bc6-bd9b-524569d9b44a # DIY Repair
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
