fieldLayouts:
  c015e9cc-e735-4ef0-b2d1-61c64f6acd9f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e1cf7603-df9a-4da9-a046-4ea2f053b31f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b5de6dcf-80e6-48e2-b846-0dab7f35c4c8 # Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d748fe42-82b2-49f7-bc9e-ec5d399f85fe
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d0e9a744-2d86-4b03-a626-2cafeaabe5a1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4a2bad07-8d89-4689-b0bf-774eed764660 # Overview title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36ecfb9a-25dd-40dd-bf07-395e285d2bc3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f8a6ddc-4ab7-4f9f-a2ea-72c6cb387f38 # Overview description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7a05ede-5943-4a71-ab25-62245802328d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 15ed2b72-8955-4cec-93f8-9736a9e50e80 # Overview image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2b5455f-b921-46cb-867f-5b294197c52d
            userCondition: null
            warning: null
            width: 100
        name: Overview
        uid: 5b80865e-e1ce-4eb2-ab93-8d0e4c2510df
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 685530fc-e1f1-4be1-813b-ebf9ac3aa108 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 52ba856b-39b7-4b5c-99c2-305da69a7347
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: bb6ad0ed-b93c-41de-9ddf-7175c2ac2d78
        userCondition: null
handle: forgotPassword
hasTitleField: true
name: 'Forgot Password'
section: 1c4e3f0f-ca9b-474d-a460-48f45133c763 # Forgot Password
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
