fieldLayouts:
  800c29b7-0814-49b8-be52-d9a68e29e533:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5892b825-a990-4a12-b329-5a0e184f7aec
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6bd903da-1e42-4c0e-a03f-2aee72ddcd72
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4a2bad07-8d89-4689-b0bf-774eed764660 # Overview title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ca0511b-cfbe-420f-aa7a-919b7d7fff84
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f8a6ddc-4ab7-4f9f-a2ea-72c6cb387f38 # Overview description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1efb4b89-248f-4199-b5ec-f14b3a41b7b5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 15ed2b72-8955-4cec-93f8-9736a9e50e80 # Overview image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e551f660-b3f1-4342-8daa-d57c4f612019
            userCondition: null
            warning: null
            width: 100
        name: Overview
        uid: afb3ddff-b010-4411-8511-b8d2df33397a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 685530fc-e1f1-4be1-813b-ebf9ac3aa108 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f338f0e9-a8b5-46df-af65-8cdf3534c2c4
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 94caea78-4376-4057-b376-601a0434ff6d
        userCondition: null
handle: profile
hasTitleField: true
name: Profile
section: 361daec5-5ea3-4d9f-957f-f39c78bb595e # Profile
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
