fieldLayouts:
  f19d5dc1-28c4-44f3-83e8-5f6e0d2ed056:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 33824d17-22b0-4c5e-81a5-e0d352eee616
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b5de6dcf-80e6-48e2-b846-0dab7f35c4c8 # Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2deff67e-fef6-45dc-9b42-3f99a03bddae
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 54457e18-21e3-4699-9428-aeb45c2aee5f # Hero image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 350550e1-ed56-4f46-9bb2-25ce47d31331
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 2b30056e-5ebb-44c1-8a21-9fc5506191b3 # Call To Action Block
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 378133b7-ed0c-43b1-b0df-68612b852c3f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 09fe45fe-1b15-4ec2-8aaa-8e43a8d2865d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4a2bad07-8d89-4689-b0bf-774eed764660 # Overview title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13f48b6f-2694-4d49-8f31-e2cf7861d52f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f8a6ddc-4ab7-4f9f-a2ea-72c6cb387f38 # Overview description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f46bd8a1-bdcc-4b58-9fa7-e9059c7af81e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 15ed2b72-8955-4cec-93f8-9736a9e50e80 # Overview image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1161063-1ed4-4ced-917d-739e58c28e3b
            userCondition: null
            warning: null
            width: 100
        name: Overview
        uid: 56e51374-42f5-483d-8445-91ef027c654c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 685530fc-e1f1-4be1-813b-ebf9ac3aa108 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a024c8e-5b81-4976-9cf8-f7841ee5b83e
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 4f4300cd-ac38-4900-a044-ad82854bb641
        userCondition: null
handle: register
hasTitleField: true
name: Register
section: 684ece64-c23a-4abf-9574-f2c053d496e8 # Register
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
