fieldLayouts:
  e06b82b0-43b0-4483-a082-511b04afce72:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4cfe909e-de55-48fa-9137-f55c0d1ca421
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b5de6dcf-80e6-48e2-b846-0dab7f35c4c8 # Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34ef59b1-51a8-4cb3-846f-fd8ad7f1b54f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 56d715d0-6a9d-4562-9c66-e5b4caad7f44 # Content Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f55530b6-1378-4ac3-92d0-dc34056581ea
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a9d0a99a-6f7e-453f-bd0d-75ac1cc9c9ce
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4a2bad07-8d89-4689-b0bf-774eed764660 # Overview title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d06fc68b-3563-4d2d-945b-667a3f003cb2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 15ed2b72-8955-4cec-93f8-9736a9e50e80 # Overview image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8d81153-0da7-4d85-a643-913a19eefba8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f8a6ddc-4ab7-4f9f-a2ea-72c6cb387f38 # Overview description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 74d47262-4b34-44e1-a689-64306bd1aae9
            userCondition: null
            warning: null
            width: 100
        name: Overview
        uid: ad3dffbb-1da8-40c3-9cf1-7e4732fab148
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 685530fc-e1f1-4be1-813b-ebf9ac3aa108 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 606f9751-0103-47dc-bae5-65e9e552bc90
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: fb9a35b8-799f-457d-b5e4-98cb023dc9b4
        userCondition: null
handle: setPasswordConfirmation
hasTitleField: true
name: 'Set Password Confirmation'
section: 4703bf34-5e13-4da1-aff6-d04c0bba024b # Set Password Confirmation
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
