defaultPlacement: end
fieldLayouts:
  de70cdfe-a4ec-4446-9fe2-ad87ff13f14c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: f835b622-7cc4-49da-bbc2-5df994f386e3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8c139417-a614-4121-95c5-0637139fdd04
        userCondition: null
handle: eventType
name: 'Event Type'
siteSettings:
  6de046f0-6167-4af1-aa91-ffaf83e36a14: # Platform
    hasUrls: false
    template: null
    uriFormat: null
  8aa67b04-5a77-45c2-a2ac-d1f65698459f: # 3D Repair FR
    hasUrls: false
    template: null
    uriFormat: null
  047f745f-3685-4496-8e78-bd0b667af2e0: # 3D Repair EN
    hasUrls: false
    template: null
    uriFormat: null
  51cad071-cea3-48ce-8809-1681b032cbd6: # Louvain La Neuve FR
    hasUrls: true
    template: null
    uriFormat: 'event-type/{slug}'
  583f2eba-5ad5-4741-b9a2-132b67b3bcaf: # 3D Repair NL
    hasUrls: false
    template: null
    uriFormat: null
  9194d239-4539-4912-ad6a-0c181ecfb860: # Leuven EN
    hasUrls: true
    template: null
    uriFormat: 'event-type/{slug}'
  74572bf4-408d-451b-bdd2-d2367f83a598: # Apeldoorn NL
    hasUrls: true
    template: null
    uriFormat: 'event-type/{slug}'
  780304c4-c532-4a30-8dc2-6890f5d60517: # Leuven NL
    hasUrls: true
    template: null
    uriFormat: 'event-type/{slug}'
  cd22acbb-24d6-4b36-94b8-5addbd7bd365: # 3D Repair DE
    hasUrls: false
    template: null
    uriFormat: null
  fc9c5d93-393d-4dfd-8d21-c9ff35643fb4: # Roeselare NL
    hasUrls: true
    template: null
    uriFormat: 'event-type/{slug}'
structure:
  maxLevels: null
  uid: b43245db-e3b8-4f6f-a808-b75b35dbd259
