defaultPlacement: end
fieldLayouts:
  bbb2332e-d0eb-449e-aae1-053d071ae52a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 8db541bf-d41d-4578-b217-8b7780f4e327
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bb9385fe-249e-4f2c-8305-d55060448917 # Category ID
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23fc2773-6550-4c49-835c-13c01a33b90f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: abdfd1d2-0eda-45d7-b016-c468bda7b5fd # Title NL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eff2c34e-e2ca-4dfc-a024-e22f6c1c7e23
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 3a8affe4-de3d-4133-9cee-41871ec34521 # Title FR
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 257e271c-6d20-414e-918d-8dce5bcec578
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 03f63c8d-ce28-4d17-887e-3587aebae8d7 # Title EN
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a3c01f0-6b22-424d-acc7-79e101e39496
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b123b2df-32b7-436e-9914-7232a28b194a # Title DE
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3fbca90d-838f-4ac0-a59f-14ea21e8896c
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: b550e4e6-9ae9-4661-90eb-19d7ca3efac1
        userCondition: null
handle: repairStatus
name: 'Repair status'
siteSettings:
  6de046f0-6167-4af1-aa91-ffaf83e36a14: # Platform
    hasUrls: true
    template: null
    uriFormat: 'repair-status/{slug}'
  8aa67b04-5a77-45c2-a2ac-d1f65698459f: # 3D Repair FR
    hasUrls: true
    template: null
    uriFormat: 'repair-status/{slug}'
  047f745f-3685-4496-8e78-bd0b667af2e0: # 3D Repair EN
    hasUrls: true
    template: null
    uriFormat: 'repair-status/{slug}'
  51cad071-cea3-48ce-8809-1681b032cbd6: # Louvain La Neuve FR
    hasUrls: true
    template: null
    uriFormat: 'repair-status/{slug}'
  583f2eba-5ad5-4741-b9a2-132b67b3bcaf: # 3D Repair NL
    hasUrls: true
    template: null
    uriFormat: 'repair-status/{slug}'
  9194d239-4539-4912-ad6a-0c181ecfb860: # Leuven EN
    hasUrls: true
    template: null
    uriFormat: 'repair-status/{slug}'
  74572bf4-408d-451b-bdd2-d2367f83a598: # Apeldoorn NL
    hasUrls: true
    template: null
    uriFormat: 'repair-status/{slug}'
  780304c4-c532-4a30-8dc2-6890f5d60517: # Leuven NL
    hasUrls: true
    template: null
    uriFormat: 'repair-status/{slug}'
  cd22acbb-24d6-4b36-94b8-5addbd7bd365: # 3D Repair DE
    hasUrls: true
    template: null
    uriFormat: 'repair-status/{slug}'
  fc9c5d93-393d-4dfd-8d21-c9ff35643fb4: # Roeselare NL
    hasUrls: true
    template: null
    uriFormat: 'repair-status/{slug}'
structure:
  maxLevels: null
  uid: 2223f98d-4d3f-447a-b8f4-184bd7a9f36f
