fieldLayouts:
  1e732d9c-fb63-457a-88f7-1ddf1c99970d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 7ad0e150-a778-478a-abc7-c2817fc3924d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 39f07216-d49a-4917-b05e-bec26f425843 # Image Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e7b5ae7-6863-4f82-83e4-8163d5a0a71f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5a25f3e9-a180-4a29-aa41-8721fbf815b9 # Optimized Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6db118fd-c7d7-41aa-8305-7524694e5a50
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0207f1a0-8ec0-4b87-9197-c1d5a9a7b61d # Optimized Overview
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82310aac-14b0-4575-97fc-5e0622ddad99
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 60b48ff5-1ab2-471b-8592-cdc623e0882c # Optimized Text Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3995a0af-a519-43de-a6af-0658bc58d2a8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 197566c6-94bb-4e67-86d7-8945f2589a1d # Optimized Hero
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e578d59-4fea-46ca-884c-ed881f9c9563
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e07f2eef-68c9-4631-88eb-fe3cb093778d
        userCondition: null
fs: backend3d
handle: backend3d
name: 'Backend 3D'
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
