fieldLayouts:
  d287882c-f314-4e21-9091-5f18d33f935d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 330a44ae-e4d4-4667-86bf-cde050f0e98d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 39f07216-d49a-4917-b05e-bec26f425843 # Image Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99febe94-9295-4ea7-a841-19efb75b3775
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5a25f3e9-a180-4a29-aa41-8721fbf815b9 # Optimized Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e31979b5-0136-465e-a0a8-5101ba5ec176
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0207f1a0-8ec0-4b87-9197-c1d5a9a7b61d # Optimized Overview
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 062bcbef-ca67-4f04-8017-b4cd0f74a825
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 60b48ff5-1ab2-471b-8592-cdc623e0882c # Optimized Text Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ccde83b-0993-43c1-9c7b-2bd01a19647d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 197566c6-94bb-4e67-86d7-8945f2589a1d # Optimized Hero
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46b1a7d4-718c-40d3-975a-2b32d7347ea2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 17e5fef0-c2f4-4c0c-ad14-07f11a91b9a3
        userCondition: null
fs: backendLeuven
handle: backendLeuven
name: 'Backend Leuven'
sortOrder: 0
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
