fieldLayouts:
  8985b5d5-d4d2-4e77-a044-b0cba33552b7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 4ac9006d-9a8c-449d-a91a-fccbf973a9be
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 39f07216-d49a-4917-b05e-bec26f425843 # Image Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f7dea17-080a-454b-98c4-b4c5c418b19a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5a25f3e9-a180-4a29-aa41-8721fbf815b9 # Optimized Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1929559-8992-45c0-bdd1-fb0fe23cd612
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 60b48ff5-1ab2-471b-8592-cdc623e0882c # Optimized Text Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e22cb8c1-2e85-4476-aabf-4cce5ae3052c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0207f1a0-8ec0-4b87-9197-c1d5a9a7b61d # Optimized Overview
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e14ade84-0e01-478f-b444-7e80dd7465d2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 197566c6-94bb-4e67-86d7-8945f2589a1d # Optimized Hero
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7555bc8f-471f-49ea-932c-c8702f5592ed
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 068ed8a0-20c6-4819-94eb-a26952e1ce0f
        userCondition: null
fs: files
handle: files
name: Files
sortOrder: 0
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
