columnSuffix: null
contentColumnType: string
fieldGroup: a66c0dc0-5fd9-4079-a773-816c9092a837 # Repair Stories
handle: additionalImage
instructions: 'You can add up to three images.'
name: 'Additional Images'
searchable: true
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: false
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:15d0b6ac-6fae-4d64-abf2-3a53ea5348ca' # Frontend
  defaultUploadLocationSubpath: '{{currentSite.group.name}}'
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 3
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:979c3eeb-f99a-4ca1-bcbe-ce9298a4e4ca' # Files
  restrictedLocationSubpath: null
  selectionLabel: 'Add an image'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
