columnSuffix: null
contentColumnType: text
fieldGroup: d45680a5-3f22-46ee-87ca-99d226b4c7bf # Organisations
handle: city
instructions: null
name: City
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: siteGroup
type: craft\fields\PlainText
