columnSuffix: null
contentColumnType: text
fieldGroup: 39b3406d-d1bb-4a84-a13a-bce5cc293238 # Globals
handle: cityName
instructions: null
name: 'Name City'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
