columnSuffix: odftqoyn
contentColumnType: string(7)
fieldGroup: 2c770290-8edc-4f26-b846-6d99d36d7844 # Common
handle: color
instructions: null
name: Color
searchable: false
settings:
  defaultColor: '#9c7a97'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
