columnSuffix: null
contentColumnType: string
fieldGroup: c5433317-7d49-4535-8c7b-894b8be40653 # Home
handle: ctaRepairCity
instructions: null
name: 'Call To Action Repair In'
searchable: true
settings:
  contentTable: '{{%matrixcontent_ctarepaircity}}'
  maxBlocks: 1
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: siteGroup
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
