columnSuffix: null
contentColumnType: string
fieldGroup: 2c770290-8edc-4f26-b846-6d99d36d7844 # Common
handle: ctas
instructions: null
name: 'Call to actions'
searchable: true
settings:
  contentTable: '{{%matrixcontent_ctas}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: none
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
