columnSuffix: null
contentColumnType: text
fieldGroup: 132b2364-c064-47f3-9187-3d5b4bd10cdb # Repair heroes
handle: function
instructions: null
name: Function
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
