columnSuffix: chixaazx
contentColumnType: text
fieldGroup: 39b3406d-d1bb-4a84-a13a-bce5cc293238 # Globals
handle: longitude
instructions: null
name: Longitude
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: siteGroup
type: craft\fields\PlainText
