columnSuffix: null
contentColumnType: text
fieldGroup: 3e2b6360-0c98-4b32-a8ec-672d54f7a09a # Events
handle: organisationName
instructions: 'Who is the organiser of this event?'
name: 'Organisation Name'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
