columnSuffix: null
contentColumnType: string
fieldGroup: 2c770290-8edc-4f26-b846-6d99d36d7844 # Common
handle: professional
instructions: null
name: Professional
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  sources:
    - 'section:7e2be3d2-532d-4b69-bcbd-9f23653a0471' # Organisations
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
