columnSuffix: ibbbhbsx
contentColumnType: string
fieldGroup: 2c770290-8edc-4f26-b846-6d99d36d7844 # Common
handle: redirectPage
instructions: 'Select the entry you want to redirect to when the form gets submitted.'
name: 'Redirect page'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: true
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  sources:
    - 'section:edafcdcc-cb6a-4636-8b06-692031d123dc' # Functionals
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
