columnSuffix: null
contentColumnType: string
fieldGroup: 2c770290-8edc-4f26-b846-6d99d36d7844 # Common
handle: repairTypes
instructions: null
name: 'Repair Types'
searchable: false
settings:
  blockTypeFields: 0
  changedFieldIndicator: null
  contentTable: '{{%stc_repairtypes}}'
  fieldLayout: matrix
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: none
  selectionLabel: null
  staticField: true
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
