columnSuffix: null
contentColumnType: string(255)
fieldGroup: 39b3406d-d1bb-4a84-a13a-bce5cc293238 # Globals
handle: twitter
instructions: null
name: Twitter
searchable: true
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: site
type: craft\fields\Url
