fieldLayouts:
  6f7fef0a-6de7-486f-887d-716ee0d2a256:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f694fce1-48ca-4bfe-9fba-196195547a36 # Facebook
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ed453bd-d5a7-4631-a100-855f8a37005a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2e4b3bb0-26e4-47d2-9445-54401a221c63 # Twitter
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df7ee082-ec2a-4c2a-8a8f-91ac77cc33ed
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ce1fab3c-0b02-49d8-8d8f-1bab2d7c05e2 # LinkedIn
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1dc64729-bc20-4bab-bd3f-ee8305b67872
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9bc4b9f2-7fc6-48b0-a3df-8e9c061a70c6 # Instagram
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 87c9eedd-d10e-4f45-9394-5d7ef3920f09
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6221c006-75b9-4fa5-a352-4cd4317fb5d7 # Youtube
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81dcf33e-2267-4382-be79-6f2c38f940ab
            userCondition: null
            warning: null
            width: 100
        name: 'Social links'
        uid: b765f52a-3569-4712-8bca-becbf51c7f61
        userCondition: null
handle: socialMedia
name: 'Social Media'
sortOrder: 5
