defaultPlacement: end
enableVersioning: true
handle: allProfessionalRepairs
name: 'All Professional Repairs'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: none
siteSettings:
  51cad071-cea3-48ce-8809-1681b032cbd6: # Louvain La Neuve FR
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  9194d239-4539-4912-ad6a-0c181ecfb860: # Leuven EN
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  74572bf4-408d-451b-bdd2-d2367f83a598: # Apeldoorn NL
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  780304c4-c532-4a30-8dc2-6890f5d60517: # Leuven NL
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  fc9c5d93-393d-4dfd-8d21-c9ff35643fb4: # Roeselare NL
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
