defaultPlacement: end
enableVersioning: true
handle: homeSharepair
name: 'Home Sharepair'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6de046f0-6167-4af1-aa91-ffaf83e36a14: # Platform
    enabledByDefault: true
    hasUrls: true
    template: indexSharepair
    uriFormat: __home__
  8aa67b04-5a77-45c2-a2ac-d1f65698459f: # 3D Repair FR
    enabledByDefault: true
    hasUrls: true
    template: indexSharepair
    uriFormat: __home__
  047f745f-3685-4496-8e78-bd0b667af2e0: # 3D Repair EN
    enabledByDefault: true
    hasUrls: true
    template: indexSharepair
    uriFormat: __home__
  583f2eba-5ad5-4741-b9a2-132b67b3bcaf: # 3D Repair NL
    enabledByDefault: true
    hasUrls: true
    template: indexSharepair
    uriFormat: __home__
  cd22acbb-24d6-4b36-94b8-5addbd7bd365: # 3D Repair DE
    enabledByDefault: true
    hasUrls: true
    template: indexSharepair
    uriFormat: __home__
type: single
