defaultPlacement: end
enableVersioning: true
handle: pageNotFound
name: 'Page not found'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6de046f0-6167-4af1-aa91-ffaf83e36a14: # Platform
    enabledByDefault: true
    hasUrls: true
    template: '404'
    uriFormat: '404'
  51cad071-cea3-48ce-8809-1681b032cbd6: # Louvain La Neuve FR
    enabledByDefault: true
    hasUrls: true
    template: '404'
    uriFormat: '404'
  9194d239-4539-4912-ad6a-0c181ecfb860: # Leuven EN
    enabledByDefault: true
    hasUrls: true
    template: '404'
    uriFormat: '404'
  74572bf4-408d-451b-bdd2-d2367f83a598: # Apeldoorn NL
    enabledByDefault: true
    hasUrls: true
    template: '404'
    uriFormat: '404'
  780304c4-c532-4a30-8dc2-6890f5d60517: # Leuven NL
    enabledByDefault: true
    hasUrls: true
    template: '404'
    uriFormat: '404'
  fc9c5d93-393d-4dfd-8d21-c9ff35643fb4: # Roeselare NL
    enabledByDefault: true
    hasUrls: true
    template: '404'
    uriFormat: '404'
type: single
