defaultPlacement: end
enableVersioning: true
handle: repairCafeRepair
name: 'Repair café repair'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  51cad071-cea3-48ce-8809-1681b032cbd6: # Louvain La Neuve FR
    enabledByDefault: true
    hasUrls: true
    template: _contentPage
    uriFormat: enregistrez-vos-reparations/repair-cafe
  9194d239-4539-4912-ad6a-0c181ecfb860: # Leuven EN
    enabledByDefault: true
    hasUrls: true
    template: _contentPage
    uriFormat: register-your-repairs/repair-cafe
  74572bf4-408d-451b-bdd2-d2367f83a598: # Apeldoorn NL
    enabledByDefault: true
    hasUrls: true
    template: _contentPage
    uriFormat: registreer-jouw-herstellingen/repair-cafe
  780304c4-c532-4a30-8dc2-6890f5d60517: # Leuven NL
    enabledByDefault: true
    hasUrls: true
    template: _contentPage
    uriFormat: registreer-jouw-herstellingen/repair-cafe
  fc9c5d93-393d-4dfd-8d21-c9ff35643fb4: # Roeselare NL
    enabledByDefault: true
    hasUrls: true
    template: _contentPage
    uriFormat: registreer-jouw-herstellingen/repair-cafe
type: single
